### ISSUE TITLE
 help me to integrate  default bpmn-js-properties-panel with bpmn.js  in my react app

### ISSUE THREAD

**Issue by mehraankush** [bpmn-io/bpmn-js-example-react-properties-panel#10]
I have seen your code 
you are customizing it 
how can i integrate this in my reactapp
![image](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/assets/96870742/561eb2e9-6fef-44c3-8df2-9c6300175fb6)

**Comment by nikku** [comment]
Thanks for opening this bug. This library specifically is how to create your own custom properties panel. What specific trouble do you have to integrate the properties panel into your React application?
