### ISSUE TITLE
Blank page when create new Item

### ISSUE THREAD

**Issue by all4u1089** [bpmn-io/bpmn-js-example-react-properties-panel#3]
__Describe the Bug__

Blank page when create new Item and hover
![Screenshot from 2020-12-31 10-17-49](https://user-images.githubusercontent.com/9291454/103392623-75757c00-4b51-11eb-9b51-eccd032d68b4.png)
![Screenshot from 2020-12-31 10-17-38](https://user-images.githubusercontent.com/9291454/103392628-78706c80-4b51-11eb-8d8f-5fb0eb0aabee.png)

__Steps to Reproduce__

1. Add new item/component
2. hover the diagram
3. all lost

__Environment__

- Host (Browser/Node version), if applicable: Chrome 86
- OS: Linux
- Library version: 8.0.0

**Comment by philippfromme** [comment]
Hint: Adding `position: 'absolute'` to the options when creating an instance will fix this issue. I've come across this a couple of times now and it's very frustrating if you don't know where to look for the fix.

Example:

```javascript
const foo = new BpmnJS({
  container: '#container',
  position: 'absolute'
});
```

**Comment by nikku** [comment]
Is this something we can improve in the example? If so @all4u1089 would you like to contribute a fix?

**Comment by eriknyk** [comment]
@all4u1089 I made form with latest version of bpmn-js, reactjs with functional base component https://github.com/eriknyk/bpmn-js-react-properties-panel-example

Diagram editor is fully functional there 

<img width="1232" alt="image" src="https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/assets/205721/d4f48d5d-d42c-4a76-b684-337f74a2ed37">

**Comment by nikku** [comment]
@eriknyk Would you like to contribute your fixes?

**Comment by eriknyk** [comment]
> @eriknyk Would you like to contribute your fixes?

Sure, I will send a PR as soon as possible

**Comment by eriknyk** [comment]
@nikku PR sent https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/pull/6

**Comment by eriknyk** [comment]
@nikku BTW I made a ported version for [svelte-js](https://kit.svelte.dev/) also https://github.com/eriknyk/bpmn-js-example-svelte-properties-panel/tree/master 

if you want make it part of `bpmn-io` I will happy to contrbute. Regards
