### ISSUE TITLE
Extend the example to demonstrate how to create custom tags along with properties.

### ISSUE THREAD

**Issue by SundaramMaheshkumar** [bpmn-io/bpmn-js-example-react-properties-panel#4]
__Extension to elements__

In React example provided [here](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel#readme), it's shown how to add custom properties to elements. But I am not sure how to add such custom tags along with properties like the one in the below example.

![image](https://user-images.githubusercontent.com/118889895/210060602-2ee29352-2a22-4ca6-9d31-3ed49c9eefc4.png)

__Example to cover the above aspect__

It would be very useful if the example covers on how to achieve such things.

Thanks!

**Comment by nikku** [comment]
We have plenty of examples including one on [custom elements](https://github.com/bpmn-io/bpmn-js-example-custom-elements#creating-a-model-extension). Did you check these out?

Another one is [embedded comments](https://github.com/bpmn-io/bpmn-js-embedded-comments).
