### ISSUE TITLE
BPMN properties panel unable to use additionalModules properly

### ISSUE THREAD

**Issue by EmersonVilar** [bpmn-io/bpmn-js-example-react-properties-panel#8]
When add additionalModules like [BpmnColorPickerModule](https://github.com/bpmn-io/bpmn-js-color-picker) and [CreateAppendAnythingModule](https://github.com/bpmn-io/bpmn-js-create-append-anything), got an error.

To reproduce: 
 - clone the [bpmn-properties-panel](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel) repo.
 - install all depencies with npm install.
 - install the two additional modules via npm and put in the code as the guides suggests.

The modules icons are present on screen:
![image](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/assets/9569197/cd2f5057-f661-4a74-a7f5-7e1770df8f71)

But, when clicked:

![image](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/assets/9569197/ee9455ba-b297-4b0e-88f0-c92686c37fd8)

I don't know what is this error related for.

- Host (Browser/Node version).
- OS: Windows 11 with Arch on WSL2.

**Comment by nikku** [comment]
> install the two additional modules via npm and put in the code as the guides suggests.

Which guide? Please share the full setup (at least your code snippet creating the BPMN editor).

**Comment by EmersonVilar** [comment]
Hi @nikku, thanks for answer me.

The guides were the "Use Extension" presented in the [BpmnColorPickerModule](https://github.com/bpmn-io/bpmn-js-color-picker/blob/main/README.md)  and [CreateAppendAnythingModule](https://github.com/bpmn-io/bpmn-js-create-append-anything/blob/main/README.md). Just:

$ npm install bpmn-js-color-picker --save
$ npm install bpmn-js-create-append-anything

And changed the [app.js](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/blob/main/src/app.js) from:

```
import Modeler from 'bpmn-js/lib/Modeler';

import PropertiesPanel from './properties-panel';

import customModdleExtension from './moddle/custom.json';

import diagramXML from './diagram.bpmn';

const $modelerContainer = document.querySelector('#modeler-container');
const $propertiesContainer = document.querySelector('#properties-container');

const modeler = new Modeler({
  container: $modelerContainer,
  moddleExtensions: {
    custom: customModdleExtension
  },
  keyboard: {
    bindTo: document.body
  }
});

const propertiesPanel = new PropertiesPanel({
  container: $propertiesContainer,
  modeler
});

modeler.importXML(diagramXML);

```

To:

```
import Modeler from 'bpmn-js/lib/Modeler';

import PropertiesPanel from './properties-panel';

import customModdleExtension from './moddle/custom.json';

import diagramXML from './diagram.bpmn';

const $modelerContainer = document.querySelector('#modeler-container');
const $propertiesContainer = document.querySelector('#properties-container');

import BpmnColorPickerModule from 'bpmn-js-color-picker';
import {
  CreateAppendAnythingModule
} from 'bpmn-js-create-append-anything';

const modeler = new Modeler({
  container: $modelerContainer,
  moddleExtensions: {
    custom: customModdleExtension
  },
  keyboard: {
    bindTo: document.body
  },
  additionalModules: [
    BpmnColorPickerModule,
    CreateAppendAnythingModule
  ]
});

const propertiesPanel = new PropertiesPanel({
  container: $propertiesContainer,
  modeler
});

modeler.importXML(diagramXML);

```

And also. change the [index.html](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/blob/main/src/index.html), from:

```
<!DOCTYPE html>
<html>
<head>
  <title>bpmn-js-react-properties-panel</title>

  <link rel="stylesheet" href="vendor/bpmn-js/assets/diagram-js.css" />
  <link rel="stylesheet" href="vendor/bpmn-js/assets/bpmn-font/css/bpmn-embedded.css" />
...

```

To:

```
<!DOCTYPE html>
<html>
<head>
  <title>bpmn-js-react-properties-panel</title>
    <link rel="stylesheet" href="https://unpkg.com/bpmn-js/dist/assets/diagram-js.css" />
    <link rel="stylesheet" href="https://unpkg.com/bpmn-js/dist/assets/bpmn-font/css/bpmn-embedded.css" />
    <link rel="stylesheet" href="https://unpkg.com/bpmn-js-color-picker/colors/color-picker.css" />
...

```

As the guide suggest.

Other than these, I do not done any other code modifications.

Hope I answered you enough.

**Comment by nikku** [comment]
Thanks. I can reproduce your issue and am investigating.

**Comment by nikku** [comment]
Problem with our webpack setup: https://github.com/bpmn-io/bpmn-js-example-react-properties-panel/pull/9.
